### ISSUE TITLE
use wget to fetch stuff (instead of Mark V)

### ISSUE THREAD

**Issue by neogeographica** [neogeographica/quakestarter#22]
- Could use Quakespasm by default instead of Mark V. The paused development on Mark V is a concern.
- Wouldn't need to work around the quirks of Mark V's mod downloader.
- If we're going to require .net 4.5 anyway (for SQL2) then we can just always use powershell to unzip stuff.
- Could fetch SQL2 instead of bundling it.

And similar to that last point, we could fetch the Quake engine(s) on demand. It would be nice just to have a manifest that describes where to get various engines from.

**Comment by neogeographica** [comment]
Or -- again, since we're assuming .net 4.5 and therefore powershell -- we could use powershell. E.g. https://superuser.com/questions/25538/how-to-download-files-from-command-line-in-windows-like-wget-or-curl

**Comment by joel-bluedata** [comment]
Some notes on fetching various Quake engines for download:

#### QuakeSpasm

DL link: https://gigenet.dl.sourceforge.net/project/quakespasm/Windows/quakespasm-0.93.0_win64.zip
actually a redirect from http://sourceforge.net/projects/quakespasm/files/Windows/quakespasm-0.93.0_win64.zip/download ; should use that if DL client can follow redirects
all files are in a folder (named quakespasm-0.93.0_win64)
executable is quakespasm.exe
(also quakespasm-sdl12.exe but we should ignore that)

#### FTE

DL link: http://fte.triptohell.info/moodles/win64/fteqw64.exe
no unzipping required

#### Mark V

DL link: http://quakeone.com/markv/builds/1036_mark_v_windows.zip
all files are top-level in archive
executables are mark_v.exe, mark_v_winquake.exe, dx9_mark_v.exe
(also dx8_mark_v.exe but we should ignore that)

**Comment by neogeographica** [comment]
Some notes on fetching various Quake engines for download:

#### QuakeSpasm

DL link: https://gigenet.dl.sourceforge.net/project/quakespasm/Windows/quakespasm-0.93.0_win64.zip
actually a redirect from http://sourceforge.net/projects/quakespasm/files/Windows/quakespasm-0.93.0_win64.zip/download ; should use that if DL client can follow redirects
all files are in a folder (named quakespasm-0.93.0_win64)
executable is quakespasm.exe
(also quakespasm-sdl12.exe but we should ignore that)

#### FTE

DL link: http://fte.triptohell.info/moodles/win64/fteqw64.exe
no unzipping required

#### Mark V

DL link: http://quakeone.com/markv/builds/1036_mark_v_windows.zip
all files are top-level in archive
executables are mark_v.exe, mark_v_winquake.exe, dx9_mark_v.exe
(also dx8_mark_v.exe but we should ignore that)

**Comment by neogeographica** [comment]
Important info to store in an engines manifest:
- Download link.
- If the download needs to be unzipped. (If so we can probably assume we should discard any containing folder.)
- A list of the included executables, just FYI.

Could also have some other info like a home webpage and a description.

The interesting part would be how to manage updates. Future releases of the quakestarter package may want to update those DL links, but this is also exactly the sort of thing someone might want to fiddle with manually.

One possible approach (may be too ambitious):

We'll deal with one manifest file per engine. Each contains the above info for that engine.

The files that come with this package will be in some sort-of-hidden resources directory. Each file is named after the engine it describes. These will have a comment at the top that says "DO NOT MODIFY" (more or less). Maybe also have a readme file in the folder that says not to modify them.

When the installer runs, it will copy all files from this directory into a more visible top-level engine_manifest directory, for each file that does not already exist in that directory. These copies will have the "DO NOT MODIFY" comment stripped out of them. The expectation is that the user may want to modify these files or add more manifest files for other engines.

When the installer actually installs an engine it only reference the info from the file in the engine_manifest directory.

If a file in the sort-of-hidden source directory has a more recent modify date than the file in the engine_manifest directory, the installer will print a message saying "hey it looks like this has been updated", show a comparison of important info between the files, and ask the user what they want to do. Choices could be:
* Ignore the difference for now. Do nothing.
* Accept the new manifest. Copy it over the old one. Optionally download and install the new engine right now.
* Permanently ignore the new manifest until it changes again. Would probably accomplish this by writing something to that new manifest file or some neighboring marker file.

**Comment by neogeographica** [comment]
Not going to do the engine-manifest stuff. Other concerns restated as part of issue #32.
