### ISSUE TITLE
Starterpack runs in error while attempting to download quoth2pt2full.zip

### ISSUE THREAD

**Issue by GenericJohnDoeNO0** [neogeographica/quakestarter#64]
The Starterpack cannot use quoth and dependent maps because the cmd tries to load a file that was deleted because of
f..k-up-while-packing.

The authors corrected their mistakes and created a new page for the download and a different file name.

The old file with errors was under http://www.quaketastic.com/files/single_player/mods/quoth2pt2full.zip (quoth2pt2full.zip),
and the new working and correct one is under https://www.quaddicted.com/filebase/quoth2pt2full_2.zip (quoth2pt2full_2.zip).

I did load the quoth2pt2full_2.zip manually, renamed it to quoth2pt2full.zip and placed it into "quakestarter_downloads" where the failed previous file (1kb) was.

Now everything runs and seems fine.

**Comment by GenericJohnDoeNO0** [comment]
The File in question is the "_handle_mod_choice.cmd"
Line 121 (This is the corrected line):
      call "%scriptspath%_install_mod.cmd" https://www.quaddicted.com/filebase/quoth2pt2full_2.zip quoth

I put the zip with the fix in here:
[quakestarter-2.2.1FIX.zip](https://github.com/neogeographica/quakestarter/files/7315464/quakestarter-2.2.1FIX.zip)

**Comment by neogeographica** [comment]
Hmm. Both those downloads work for me and result in byte-for-byte identical files. Maybe quaketastic was down for a bit?

I'll probably change it to use quaddicted anyway for consistency.
