### ISSUE TITLE
Contact me

### ISSUE THREAD

**Issue by ghost** [neogeographica/quakestarter#74]
I have build a worth code with more 9000 line code batch with your same objectif 
add me on discord FranckySnow#0820 .

My batch totaly protect by password and my server.  I think it may interest you.
you can copy my ideas if you want there is no problem.

+100 mods with database all acces batch delete clear and more tips...

**Comment by neogeographica** [comment]
Hey thanks for getting in touch!

I'm not planning on any big changes to Quakestarter in the immediate future, and I think it's in a pretty good place. If your project is in a repo somewhere I'd be happy to take a peek but otherwise I'm going to be turning my attention to other things for a while.
